# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_auto_20170513_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.IntegerField(default=0, max_length=32, verbose_name='博客主题'),
        ),
    ]
