# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20170513_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
    ]
