# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_auto_20170515_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm', to='repository.UserInfo', verbose_name='评论者'),
        ),
    ]
